Moved `setup_register` to forward because of gradients.
Took me a while to figure this out, but if I kept building the base seq
only once, I would get problems with the gradients.
It was always:
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```